apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # base ArgoCD components
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.3/manifests/install.yaml

components:
  # extensions controller component
  - https://github.com/argoproj-labs/argocd-extensions/manifests
