---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dome-dss-secret
  namespace: ssi
spec:
  encryptedData:
    certificate-password: AgCydUPdk1fVmT0bGcdyZcjXU7kcpuGZrUkeCv49S9wOSKgQDFqJGIHs7HOtqU14tfub12bIDG6uth0cyf/5c6XTLmZxUBhjOFn9YCW3Psij/eJl6kE2sSkp3kD5kl68kRvkzuZk3Np/K4zePZhWATP68QTPInc7jNIE4M/630KB4vGkhfSRoYtn/n6Qb7+xELvn/093kHluSnVWeYF9+RLwO/7in3oJbMOV2QKgAUUD4g4nZhj6S5iVdNeBKE3+LpVYdlWcTvKNFt+argMzohlVOZEjurprxUXC1HxYwGGq/qW2FdDrUQYI1//WwjIMMazzPrdzQElzKFBR93U+82/T4e3qzfFBaZFgmOQKQhCZoTZxztGMoBPsIq+gX/+3TMzPpP5IpGfmdj+z8B1cDFeE4E3DOI/rSLtAvTNdOGi0cWkO963DidIRV5xJCrJVjCeAVuvAhHTPKiO5L7MawtgoitBBHr8mmLLhFpe2oTJVQiUhbHQjzhQ+6UYwh6A7xsGyORtJx8HTUSRdw4gfIFDOTbuZuOdRrfFh4X+/5zw3JJN96b56oCUsLBDXbXuO2guVkTMudpwBxGW9m162WOfBUe9/oAi+leaqewRC5WxiIiItmENdFoSYtMnErCacC5OqkyJ/DQJlwAzVMvtI+vR1UqrMaXjGbAIwrW29ef242XGoSTKhU/N7okQOR9zWkYvgRiZ9ERB24NGm96OK2S8gVMtM9g==
  template:
    metadata:
      creationTimestamp: null
      name: dome-dss-secret
      namespace: ssi
