apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd  
  labels:
    purpose: infra
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: core/cert-manager
    repoURL: https://github.com/in2workspace/in2-ssihub-staging-gitops
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-env.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true