apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
  labels:
    purpose: infra
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: core/namespaces
    repoURL: https://github.com/in2workspace/in2-ssihub-staging-gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true