---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: verifier-secret
  namespace: ssi
spec:
  encryptedData:
    private-key: AgAthQ8uy0F6ro7eqR3GlI1ylbO7fbQtFihSyX0ymluV4l+JkfkKShZJI7EusiKR7wtqhC3E7bzviLCmNTorl1GLEHkq7r2bwrGzVdgUumT3sD5jmnZoNaw4qPSbYG0p4x5PBBWvjGngv5hy9cYXNDaujGWdaqIrFOvg4feZDAhL4S57DEq1WcgYVRPngL4Bdc3pCX2BQpk4UU3tHovpCt0egClxVhvrxcFa7QFhUaw8JJ80hOmYpRJ6yVEQT8CgF9Juime+ggLfcgzKwB4IxyI2UGMMOD6fAK6th1+rNhqYFt2fBECF+9UEilrYFVa53XXIYvqmPR99hHuuNVq1naFrVPnrUNXBVVajCzXEyA8dwptFIGxL/+laKbZOo8du/LhZqifZzY/7ItvS6QYsgqRm8BzBPPXFprUJIH55HGOOU1IrNP/Gj3LzDNP32UZ2Oob3y1yP7wF4oAZxAQ1hM9IVDxmIo238hR5lPPLxnWRdLfBRO/mmseSvbVNKP8rZVoLfDdEvtUNU7sG6wFsnvBsuptMRQ+pAGVjS9yVKj09O2yTeI58h0Bek+QR+irnNFwVwH+IsmWPqy+C0qe8dFTshZlYqhUtSzukMoX9TuawKZV0JV9+u0zVoxV+17p/9Zw3ABFYyQ4OMIdzS7adfMnKOVHrdkxWXMI91mlJ/ZTZp+6Rr+b0ncc3wwpTIShs/4R4+94dRP6Kf02NiqSMA9DMVc60srWlc4Dl0Fk1FZc1/wv5yubFZpi3/e0WCzylKDJp6DeXnZ6/1jrdvM6GTw1E0ve4=
  template:
    metadata:
      creationTimestamp: null
      name: verifier-secret
      namespace: ssi
