---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: verifier-secret
  namespace: iam
spec:
  encryptedData:
    private-key: AgA/ojbfZzrrSUrv9YjrsPemBAQC7OCUsQbOnPW1YyM5blN6rjzeZeQjHMR2ont9pO1zcUgqhBidV9zIldy+zQ/p4t5EuJBMcTowV5KhdLwZ20O9lC+IygEU3xnTX9++iggent11tQaB3qRMEjwWx1ExLelmGz4jPWv606OB443qbYknnKzYGNpuyYdeORr0ERwwQkQrkSIeGzeWemmxqWQ69s36iaiKpGBas9+ExxD4s4Jcun7kIzcNK4epbw/MuR9Y3wPQd6TYxHBifJbbOaV5dZsI6WUODbeZ0LZwBXIM/bmdpATu8DRixDrvV1zOdrSlO7erRE5EaNDS84S8iDbJh3xRT6FshG8OFalgWhJDH2Ag5BV4xB5FffADU+i5V0jdH6tovJY5CYsJFWI8tvMNOuXLHDBR5CKDyIM+F8q91Kj9f7DvSoBDQJobnl9zyS2IVkNdPbOSEQEMXWVUxcD3N6dkoRnzHdFsFbTZ4dqJvJwlm1ejHw3Y7gND8Laxgc16jvGy3FXWFahx/Q0JvV+TUTRzfaODAF6D2ya3l1YviRQo1e/XwW5RydyjORaOk9L0tVKRy+0G8V32Orlweme7SOKfNwIOz9MmOl0jgXaHn9ffWC5+3VH6R7bxYz0mm4D5PwTmjDR9DG/RANeO3A22QeSXcWlw/821B5w9oQj8CYivUQnjup81RQfWndEJ05cohWyBs0GvXJ4WpNyP5IbpYBWZw2NGbl3hCoLm9Y3EdHgLiZovE5PH3q0cLUC4IBawpHE+1MVHdOm2hvpERnOW574=
  template:
    metadata:
      creationTimestamp: null
      name: verifier-secret
      namespace: iam
